### PR TITLE
update eclipse base and tycho versions

### PR DESCRIPTION
**Pull request by gyorb**

### CODE REVIEW

**Comment by Vodorok** [comment]
Looks good to me!
Builds, and seems to be working, on Eclipse Neon 3. 
@gyorb Have you tried with any other version?

**Comment by gyorb** [comment]
Not yet, but I will check.

**Comment by gyorb** [comment]
I've tested with Oxygen 3, Photon and it works.

**Comment by gyorb** [comment]
PR #167 updates tycho to a newer version, this is not required.

**Pull request closed without merging**
